// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to regenerate from the endpoint manifest.
/* eslint-disable */
import * as q from "../params.js";
import type * as Types from "../types.js";
import type { ClientCore } from "../client.js";
import type { RequestOptions } from "../http.js";

export class Muhurta {
  constructor(private readonly _c: ClientCore) {}

  /** Best-scoring general muhurta window in a date range. */
  bestTime<T = unknown>(input: Types.MuhurtaInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/best-time", q.qMuhurta(input), opts);
  }

  /** Compute Chandra Bala — the Moon's strength relative to a person's natal Moon sign on a given date. */
  chandraBala<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { birthMoonSign: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/chandra-bala", q.applyExtras(q.qBirth(input), input, [["birthMoonSign", "birth_moon_sign"]]), opts);
  }

  /** Find auspicious Griha Pravesh (housewarming) muhurta windows in a date range — checks tithi, nakshatra, vara, Sun position, and lagna for the ceremony. */
  grahaPravesh<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/graha-pravesh", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }

  /** Naamkaran (naming ceremony) muhurta windows. */
  naamkaran<T = unknown>(input: Types.MuhurtaInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/naamkaran", q.qMuhurta(input), opts);
  }

  /** Find Panchaka-free (Panchaka Rahita) windows in a date range — Panchaka occurs when Moon is in Aquarius or Pisces and creates obstacles for travel, construction, funerals, and certain ceremonies. */
  panchakaRahita<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/panchaka-rahita", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }

  /** Find Sarvartha Siddhi Yoga windows — one of the most auspicious panchang yogas formed by specific vara+nakshatra combinations. */
  sarvarthaSiddhi<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/sarvartha-siddhi", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }

  /** Find Shubha Yoga (auspicious panchang yoga) windows in a date range — checks for Amrit Siddhi, Sarvartha Siddhi, Ravi Yoga, and other classical panchang yogas in combination. */
  shubhaYoga<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/shubha-yoga", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }

  /** Compute Tara Bala score for a given date relative to a person's birth nakshatra — rates the day's Moon nakshatra as Janma/Sampat/Vipat/Kshema/Pratyak/Sadhana/Vadha/Mitra/Param-Mitra. */
  taraBala<T = unknown>(input: Types.BirthInput & Types.VedicBirthSettings & { birthNak: number }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/tara-bala", q.applyExtras(q.qBirth(input), input, [["birthNak", "birth_nak"]]), opts);
  }

  /** Auspicious wedding (vivah) muhurta windows in a date range. */
  vivah<T = unknown>(input: Types.MuhurtaInput, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/vivah", q.qMuhurta(input), opts);
  }

  /** Find auspicious Vyapar (business/trade) muhurta windows — suitable for starting a business, signing contracts, launching a product, or opening a shop. */
  vyapar<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/vyapar", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }

  /** Find auspicious Yatra (travel/journey) muhurta windows — avoids Disha Shool (directional inauspiciousness), Rahu Kaal, Nak Shool, and favours Pushya/Hasta/Ashwini/Anuradha nakshatras for journeys. */
  yatra<T = unknown>(input: { lat: number; lon: number; tz: string; startDate: string; endDate: string }, opts?: RequestOptions): Promise<T> {
    return this._c.request<T>("/v1/muhurta/yatra", q.applyExtras(q.qNone(input), input, [["lat", "lat"], ["lon", "lon"], ["tz", "tz"], ["startDate", "start_date"], ["endDate", "end_date"]]), opts);
  }
}
